# Generated by Django 5.1.3 on 2024-12-06 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='income',
            fields=[
                ('income_id', models.AutoField(primary_key=True, serialize=False)),
                ('income_amount', models.CharField(max_length=100)),
                ('income_source', models.CharField(max_length=100)),
                ('income_date', models.DateField()),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
